### ISSUE TITLE
json_cmd not working as intended

### ISSUE THREAD

**Issue by franalbani** [aborrero/python-nftables-tutorial#4]
Hi! Sorry for using this place for reporting this issue, as I'm aware the problem is not here.

I wanted to share this analysis with you because you may already know where the problem is.

I was translating some nft cli bash scripts to python and tried to apply what I learned in https://man.archlinux.org/man/extra/nftables/libnftables-json.5.en , but I could not make it work.

I made a repo with the minimal example that shows the difference: https://github.com/franalbani/nftableson

Thanks for your time and forgive me if this is inappropriate.

**Comment by aborrero** [comment]
Please reach out to netfilter@vger.kernel.org for user support, or try IRC #netfilter @ libera.chat
