### ISSUE TITLE
Are non-Debian systems supported?

### ISSUE THREAD

**Issue by gustad** [aborrero/python-nftables-tutorial#5]
>In Debian systems, the nftables python module is included in the python3-nftables package

 Is there a git repository or pip installable package for python3-nftables which can be used for non-Debian systems?

**Comment by fargburger** [comment]
it's just `pip3 install nftables`

**Comment by gustad** [comment]
Thanks, but I'm not able to do that:
```
$ pip3 install nftables
ERROR: Could not find a version that satisfies the requirement nftables (from versions: none)
ERROR: No matching distribution found for nftables
```
However, I'm able to pip install matplotlib and others.

**Comment by aborrero** [comment]
I only use Debian. For other systems, you better check their documentation and package listing.
